
import React, { createContext, useState, useContext } from 'react';

const translations = {
  es: {
    // --- GENERAL Y UI ---
    nav_nosotros: "Nosotros",
    nav_servicios: "Servicios",
    nav_contacto: "Contacto",
    btn_more_info: "Más información",
    btn_contact: "Contactar Ahora",
    service_not_found: "Servicio no encontrado.",
    what_includes: "¿Qué incluye el servicio?",
    our_differential: "Nuestro Diferencial",
    cta_ready_title: "¿Listo para comenzar la transformación?",
    cta_ready_desc: "Agenda una reunión diagnóstica hoy mismo.",

    // --- HERO BANNER ---
    hero_title: "Transformación Consciente para tu Organización",
    hero_subtitle: "Coaching ontológico, desarrollo de liderazgo y estrategias de ventas para potenciar tu negocio y bienestar sostenibles.",
    hero_cta: "Inicia tu transformación",
    hero_title2: "Cultura y Resultados",
    hero_subtitle2: "Un abordaje 360° para transformar tu organización de manera integral.",
    hero_cta2: "Ver Programas Integrales",
    promo_bar: "Descubre el poder de nuestros Programas Integrales 360° para empresas.",

    // --- SECCIONES INFORMATIVAS (Home) ---
    importance_title: "Importancia del Coaching en la Actualidad",
    importance_desc: "En un mundo en constante cambio, el coaching se ha convertido en una herramienta esencial para el desarrollo personal y profesional. Permite a individuos y organizaciones adaptarse, crecer y alcanzar su máximo potencial mediante conversaciones transformadoras y metodologías probadas.",
    results_title: "¿Qué resultados se obtienen con nuestros servicios?",
    results_desc: "Incremento en la productividad, mejora en la comunicación interna, desarrollo del liderazgo, aumento en las ventas y una cultura organizacional sólida y alineada con los objetivos del negocio. Nuestros clientes reportan resultados tangibles desde las primeras sesiones.",

    // --- FORMULARIO DE CONTACTO ---
    form_title: "Trabajemos Juntos",
    lbl_nombre: "Nombre completo",
    lbl_empresa: "Empresa / Organización (Opcional)",
    lbl_email: "Correo electrónico",
    lbl_tel: "Teléfono de contacto",
    lbl_msg: "Cuéntanos sobre tus necesidades o las de tu equipo...",
    lbl_policy: "He leído y acepto la política de privacidad.",
    btn_send: "Enviar Mensaje",
    form_success: "¡Mensaje Enviado!",
    form_success_text: "Hemos recibido tu consulta. Nos pondremos en contacto contigo a la brevedad.",
    form_error: "Error de envío",
    form_error_text: "Hubo un problema de conexión. Por favor, intenta enviar tu mensaje nuevamente más tarde.",
    val_name_title: "Nombre muy corto",
    val_name_text: "El nombre debe tener al menos 5 caracteres.",
    val_email_title: "Email inválido",
    val_email_text: "Por favor ingresa un correo electrónico con un formato válido.",
    val_policy_title: "Acepta los términos",
    val_policy_text: "Debes aceptar la política de privacidad para poder enviar tu mensaje.",

    // --- NOSOTROS (About Us) ---
    about_title: "Conocé Euno ",
    about_subtitle: "Impulsamos personas. Potenciamos resultados.",
    mision_title: "Misión",
    mision_desc: "Transformar empresas y potenciar marcas personales a través de la integración orgánica del coaching ontológico, la gestión emocional, el marketing y las ventas, generando estrategias conscientes, conversaciones efectivas y acciones que impulsen resultados extraordinarios con bienestar sostenible.",
    vision_title: "Visión",
    vision_desc: "Ser la consultora referente en Latinoamérica en la humanización de los negocios, demostrando que la transparencia, la alegría y la conciencia son la base de una rentabilidad sostenible, equipos comprometidos y marcas personales sólidas.",
    valores_title: "Nuestros Valores",
    
    val_honestidad: "Honestidad",
    val_honestidad_desc: "Coherencia total entre lo que decimos y hacemos.",
    val_transparencia: "Transparencia",
    val_transparencia_desc: "Procesos claros, comunicación abierta y sin 'letras chiquitas'.",
    val_alegria: "Alegría",
    val_alegria_desc: "Creemos en el bienestar emocional como motor del éxito profesional y organizacional.",
    val_pasion: "Pasión",
    val_pasion_desc: "Nos moviliza lo que hacemos y lo transmitimos en cada proceso y resultado.",
    val_posibilidad: "Posibilidad",
    val_posibilidad_desc: "Confiamos en el potencial de las personas y en la capacidad de crear nuevas realidades.",
    val_equipo: "Trabajo en equipo",
    val_equipo_desc: "Fomentamos la colaboración genuina para potenciar resultados e impacto.",
    val_prosperidad: "Prosperidad colectiva",
    val_prosperidad_desc: "El éxito es real cuando beneficia a todas las partes involucradas (Ganar-Ganar).",
    val_conciencia: "Conciencia",
    val_conciencia_desc: "Toda transformación comienza con una nueva forma de observar.",
    val_resultados: "Orientación a resultados",
    val_resultados_desc: "Diseñamos acciones que impactan tanto en el negocio como en las personas.",

    // --- SERVICIOS (Detalles) ---
    serv_ind_title: "Coaching Individual",
    serv_ind_subtitle: "Ontológico & Desarrollo Personal",
    serv_ind_tagline: "Enfocado en personas que quieren generar cambios concretos en su vida personal o profesional.",
    serv_ind_item1: "Procesos de coaching ontológico 1:1",
    serv_ind_item2: "Gestión emocional aplicada a la vida cotidiana",
    serv_ind_item3: "Acompañamiento en toma de decisiones",
    serv_ind_item4: "Desarrollo de autoconocimiento y liderazgo personal",
    serv_ind_item5: "Reconfiguración de creencias limitantes",
    serv_ind_item6: "Coaching para momentos de cambio (laboral, personal, crisis, etc.)",
    serv_ind_dif1: "Integración de coaching ontológico + psicoeducación + neurociencias",
    serv_ind_dif2: "Trabajo profundo en lenguaje, emociones y cuerpo",
    serv_ind_dif3: "Herramientas prácticas y aplicables desde la primera sesión",

    serv_eje_title: "Coaching Ejecutivo",
    serv_eje_subtitle: "Liderazgo & Alta Exigencia",
    serv_eje_tagline: "Orientado a líderes, mandos medios y perfiles con responsabilidad de gestión.",
    serv_eje_item1: "Coaching para desarrollo de liderazgo",
    serv_eje_item2: "Gestión emocional en entornos de alta exigencia",
    serv_eje_item3: "Toma de decisiones estratégicas",
    serv_eje_item4: "Desarrollo de habilidades conversacionales (feedback, pedidos, conversaciones difíciles)",
    serv_eje_item5: "Acompañamiento en procesos de cambio organizacional",
    serv_eje_item6: "Coaching para mejora de desempeño y resultados",
    serv_eje_dif1: "Enfoque ontológico aplicado al negocio",
    serv_eje_dif2: "Integración de inteligencia emocional + mirada sistémica",
    serv_eje_dif3: "Trabajo sobre el impacto del líder en el clima y resultados",

    serv_org_title: "Coaching Organizacional",
    serv_org_subtitle: "Cultura & Vínculos Internos",
    serv_org_tagline: "Para empresas que buscan mejorar cultura, resultados y vínculos internos.",
    serv_org_item1: "Diagnóstico cultural y conversacional",
    serv_org_item2: "Intervenciones en equipos de trabajo",
    serv_org_item3: "Programas de liderazgo organizacional",
    serv_org_item4: "Mejora del clima laboral",
    serv_org_item5: "Gestión de conflictos y mediación",
    serv_org_item6: "Diseño de conversaciones efectivas en la organización",
    serv_org_dif1: "Abordaje desde la cultura y no solo desde la conducta",
    serv_org_dif2: "Intervenciones prácticas con impacto en resultados",
    serv_org_dif3: "Integración de coaching + emocionalidad + negocio",

    serv_mentoria_title: "Mentorías en Ventas",
    serv_mentoria_subtitle: "Identidad & Cierre Comercial",
    serv_mentoria_tagline: "Para vendedores, emprendedores o equipos comerciales.",
    serv_mentoria_item1: "Mentorías 1:1 para vendedores",
    serv_mentoria_item2: "Acompañamiento en procesos de cierre",
    serv_mentoria_item3: "Desarrollo de habilidades comerciales",
    serv_mentoria_item4: "Gestión emocional en ventas (rechazo, frustración, presión por objetivos)",
    serv_mentoria_item5: "Construcción de identidad comercial",
    serv_mentoria_item6: "Estrategias de fidelización y experiencia del cliente",
    serv_mentoria_dif1: "Trabajo sobre el 'ser vendedor', no solo técnicas",
    serv_mentoria_dif2: "Integración de coaching + ventas + emocionalidad",
    serv_mentoria_dif3: "Foco en resultados sostenibles (no solo scripts)",

    serv_cap_title: "Capacitaciones en Ventas",
    serv_cap_subtitle: "Entrenamiento Comercial Corporativo",
    serv_cap_tagline: "Para equipos comerciales de empresas.",
    serv_cap_item1: "Programas de formación en ventas",
    serv_cap_item2: "Técnicas de cierre y negociación",
    serv_cap_item3: "Experiencia del cliente (CX)",
    serv_cap_item4: "Comunicación efectiva en ventas",
    serv_cap_item5: "Manejo de objeciones",
    serv_cap_item6: "Venta consultiva",
    serv_cap_item7: "Entrenamiento en habilidades blandas para vendedores",
    serv_cap_dif1: "Capacitaciones vivenciales (no teóricas)",
    serv_cap_dif2: "Integración de coaching ontológico",
    serv_cap_dif3: "Aplicación directa al puesto de trabajo",
    serv_cap_dif4: "Enfoque en NPS y calidad de atención",

    serv_int_title: "Programas Integrales",
    serv_int_subtitle: "Abordaje 360° Premium",
    serv_int_tagline: "Propuesta premium para organizaciones centrado en Coaching + Ventas + Cultura.",
    serv_int_item1: "Programas de transformación cultural",
    serv_int_item2: "Alineación entre liderazgo y equipos comerciales",
    serv_int_item3: "Integración de gestión emocional en ventas",
    serv_int_item4: "Desarrollo de cultura centrada en el cliente",
    serv_int_item5: "Seguimiento + medición de impacto",
    serv_int_dif1: "Abordaje holístico y simultáneo de los tres ejes del éxito corporativo",
    serv_int_dif2: "Mediciones precisas de clima, conversión de ventas y efectividad operativa"
  },
  
  en: {
    // --- GENERAL Y UI ---
    nav_nosotros: "About Us",
    nav_servicios: "Services",
    nav_contacto: "Contact",
    btn_more_info: "More information",
    btn_contact: "Contact Now",
    service_not_found: "Service not found.",
    what_includes: "What does the service include?",
    our_differential: "Our Differential",
    cta_ready_title: "Ready to start the transformation?",
    cta_ready_desc: "Schedule a diagnostic meeting today.",

    // --- HERO BANNER ---
    hero_title: "Conscious Transformation for Your Organization",
    hero_subtitle: "Ontological coaching, leadership development, and sales strategies to boost your business and sustainable well-being.",
    hero_cta: "Start your transformation",
    hero_title2: "Culture and Results",
    hero_subtitle2: "A 360° approach to comprehensively transform your organization.",
    hero_cta2: "View Comprehensive Programs",
    promo_bar: "Discover the power of our 360° Comprehensive Programs for companies.",

    // --- SECCIONES INFORMATIVAS (Home) ---
    importance_title: "The Importance of Coaching Today",
    importance_desc: "In a constantly changing world, coaching has become an essential tool for personal and professional development. It enables individuals and organizations to adapt, grow, and reach their full potential through transformative conversations and proven methodologies.",
    results_title: "What results are achieved with our services?",
    results_desc: "Increased productivity, improved internal communication, leadership development, increased sales, and a solid organizational culture aligned with business objectives. Our clients report tangible results from the very first sessions.",

    // --- FORMULARIO DE CONTACTO ---
    form_title: "Let's Work Together",
    lbl_nombre: "Full Name",
    lbl_empresa: "Company / Organization (Optional)",
    lbl_email: "Email Address",
    lbl_tel: "Phone Number",
    lbl_msg: "Tell us about your needs or your team's needs...",
    lbl_policy: "I have read and accept the privacy policy.",
    btn_send: "Send Message",
    form_success: "Message Sent!",
    form_success_text: "We have received your inquiry. We will get back to you shortly.",
    form_error: "Sending Error",
    form_error_text: "There was a connection problem. Please try sending your message again later.",
    val_name_title: "Name too short",
    val_name_text: "The name must have at least 5 characters.",
    val_email_title: "Invalid email",
    val_email_text: "Please enter a valid email address.",
    val_policy_title: "Accept terms",
    val_policy_text: "You must accept the privacy policy to send your message.",

    // --- NOSOTROS (About Us) ---
    about_title: "Get to know Euno 360",
    about_subtitle: "We empower people. We boost results.",
    mision_title: "Mission",
    mision_desc: "To transform companies and boost personal brands through the organic integration of ontological coaching, emotional management, marketing, and sales, generating conscious strategies, effective conversations, and actions that drive extraordinary results with sustainable well-being.",
    vision_title: "Vision",
    vision_desc: "To be the leading consultancy in Latin America in the humanization of business, demonstrating that transparency, joy, and awareness are the foundation of sustainable profitability, committed teams, and solid personal brands.",
    valores_title: "Our Values",
    
    val_honestidad: "Honesty",
    val_honestidad_desc: "Total coherence between what we say and what we do.",
    val_transparencia: "Transparency",
    val_transparencia_desc: "Clear processes, open communication without 'small print'.",
    val_alegria: "Joy",
    val_alegria_desc: "We believe in emotional well-being as the engine of professional and organizational success.",
    val_pasion: "Passion",
    val_pasion_desc: "We are moved by what we do, and we transmit it in every process and result.",
    val_posibilidad: "Possibility",
    val_posibilidad_desc: "We trust in people's potential and the capacity to create new realities.",
    val_equipo: "Teamwork",
    val_equipo_desc: "We foster genuine collaboration to boost results and impact.",
    val_prosperidad: "Collective Prosperity",
    val_prosperidad_desc: "Success is real when it benefits all parties involved (Win-Win).",
    val_conciencia: "Awareness",
    val_conciencia_desc: "Every transformation begins with a new way of observing.",
    val_resultados: "Results-Oriented",
    val_resultados_desc: "We design actions that impact both the business and the people.",

    // --- SERVICIOS (Detalles) ---
    serv_ind_title: "Individual Coaching",
    serv_ind_subtitle: "Ontological & Personal Development",
    serv_ind_tagline: "Focused on people who want to generate concrete changes in their personal or professional lives.",
    serv_ind_item1: "1:1 Ontological coaching processes",
    serv_ind_item2: "Emotional management applied to daily life",
    serv_ind_item3: "Support in decision making",
    serv_ind_item4: "Development of self-knowledge and personal leadership",
    serv_ind_item5: "Reconfiguration of limiting beliefs",
    serv_ind_item6: "Coaching for moments of change (work, personal, crisis, etc.)",
    serv_ind_dif1: "Integration of ontological coaching + psychoeducation + neurosciences",
    serv_ind_dif2: "Deep work on language, emotions, and body",
    serv_ind_dif3: "Practical and applicable tools from the first session",

    serv_eje_title: "Executive Coaching",
    serv_eje_subtitle: "Leadership & High Demand",
    serv_eje_tagline: "Oriented to leaders, middle management, and profiles with management responsibility.",
    serv_eje_item1: "Coaching for leadership development",
    serv_eje_item2: "Emotional management in highly demanding environments",
    serv_eje_item3: "Strategic decision making",
    serv_eje_item4: "Development of conversational skills (feedback, requests, difficult conversations)",
    serv_eje_item5: "Support in organizational change processes",
    serv_eje_item6: "Coaching for performance and results improvement",
    serv_eje_dif1: "Ontological approach applied to the business",
    serv_eje_dif2: "Integration of emotional intelligence + systemic view",
    serv_eje_dif3: "Work on the leader's impact on climate and results",

    serv_org_title: "Organizational Coaching",
    serv_org_subtitle: "Culture & Internal Relationships",
    serv_org_tagline: "For companies looking to improve culture, results, and internal relationships.",
    serv_org_item1: "Cultural and conversational diagnosis",
    serv_org_item2: "Interventions in work teams",
    serv_org_item3: "Organizational leadership programs",
    serv_org_item4: "Improvement of the work environment",
    serv_org_item5: "Conflict management and mediation",
    serv_org_item6: "Design of effective conversations in the organization",
    serv_org_dif1: "Approach from culture and not just behavior",
    serv_org_dif2: "Practical interventions with impact on results",
    serv_org_dif3: "Integration of coaching + emotionality + business",

    serv_mentoria_title: "Sales Mentoring",
    serv_mentoria_subtitle: "Identity & Commercial Closing",
    serv_mentoria_tagline: "For salespeople, entrepreneurs, or commercial teams.",
    serv_mentoria_item1: "1:1 Mentoring for salespeople",
    serv_mentoria_item2: "Support in closing processes",
    serv_mentoria_item3: "Development of commercial skills",
    serv_mentoria_item4: "Emotional management in sales (rejection, frustration, pressure for objectives)",
    serv_mentoria_item5: "Construction of commercial identity",
    serv_mentoria_item6: "Customer loyalty and experience strategies",
    serv_mentoria_dif1: "Work on 'being a salesperson', not just techniques",
    serv_mentoria_dif2: "Integration of coaching + sales + emotionality",
    serv_mentoria_dif3: "Focus on sustainable results (not just scripts)",

    serv_cap_title: "Sales Training",
    serv_cap_subtitle: "Corporate Commercial Training",
    serv_cap_tagline: "For corporate commercial teams.",
    serv_cap_item1: "Sales training programs",
    serv_cap_item2: "Closing and negotiation techniques",
    serv_cap_item3: "Customer Experience (CX)",
    serv_cap_item4: "Effective communication in sales",
    serv_cap_item5: "Handling objections",
    serv_cap_item6: "Consultative selling",
    serv_cap_item7: "Soft skills training for salespeople",
    serv_cap_dif1: "Experiential training (not theoretical)",
    serv_cap_dif2: "Integration of ontological coaching",
    serv_cap_dif3: "Direct application to the workplace",
    serv_cap_dif4: "Focus on NPS and quality of care",

    serv_int_title: "Comprehensive Programs",
    serv_int_subtitle: "Premium 360° Approach",
    serv_int_tagline: "Premium proposal for organizations focused on Coaching + Sales + Culture.",
    serv_int_item1: "Cultural transformation programs",
    serv_int_item2: "Alignment between leadership and commercial teams",
    serv_int_item3: "Integration of emotional management in sales",
    serv_int_item4: "Development of a customer-centric culture",
    serv_int_item5: "Tracking + impact measurement",
    serv_int_dif1: "Holistic and simultaneous approach to the three axes of corporate success",
    serv_int_dif2: "Precise measurements of climate, sales conversion, and operational effectiveness"
  },

  pt: {
    // --- GENERAL Y UI ---
    nav_nosotros: "Sobre Nós",
    nav_servicios: "Serviços",
    nav_contacto: "Contato",
    btn_more_info: "Mais informações",
    btn_contact: "Contate Agora",
    service_not_found: "Serviço não encontrado.",
    what_includes: "O que o serviço inclui?",
    our_differential: "Nosso Diferencial",
    cta_ready_title: "Pronto para iniciar a transformação?",
    cta_ready_desc: "Agende uma reunião diagnóstica hoje mesmo.",

    // --- HERO BANNER ---
    hero_title: "Transformação Consciente para sua Organização",
    hero_subtitle: "Coaching ontológico, desenvolvimento de liderança e estratégias de vendas para impulsionar seu negócio e bem-estar sustentável.",
    hero_cta: "Inicie sua transformação",
    hero_title2: "Cultura e Resultados",
    hero_subtitle2: "Uma abordagem 360° para transformar sua organização de forma integral.",
    hero_cta2: "Ver Programas Integrais",
    promo_bar: "Descubra o poder de nossos Programas Integrais 360° para empresas.",

    // --- SECCIONES INFORMATIVAS (Home) ---
    importance_title: "A Importância do Coaching Hoje",
    importance_desc: "Em um mundo em constante mudança, o coaching tornou-se uma ferramenta essencial para o desenvolvimento pessoal e profissional. Permite que indivíduos e organizações se adaptem, cresçam e alcancem seu potencial máximo através de conversas transformadoras e metodologias comprovadas.",
    results_title: "Quais resultados são obtidos com nossos serviços?",
    results_desc: "Aumento da produtividade, melhoria na comunicação interna, desenvolvimento da liderança, aumento nas vendas e uma cultura organizacional sólida alinhada aos objetivos do negócio. Nossos clientes relatam resultados tangíveis desde as primeiras sessões.",

    // --- FORMULARIO DE CONTACTO ---
    form_title: "Vamos Trabalhar Juntos",
    lbl_nombre: "Nome completo",
    lbl_empresa: "Empresa / Organização (Opcional)",
    lbl_email: "Endereço de e-mail",
    lbl_tel: "Telefone de contato",
    lbl_msg: "Conte-nos sobre suas necessidades ou as da sua equipe...",
    lbl_policy: "Li e aceito a política de privacidade.",
    btn_send: "Enviar Mensagem",
    form_success: "Mensagem Enviada!",
    form_success_text: "Recebemos sua consulta. Entraremos em contato em breve.",
    form_error: "Erro de Envio",
    form_error_text: "Houve um problema de conexão. Por favor, tente enviar sua mensagem novamente mais tarde.",
    val_name_title: "Nome muito curto",
    val_name_text: "O nome deve ter pelo menos 5 caracteres.",
    val_email_title: "E-mail inválido",
    val_email_text: "Por favor, insira um endereço de e-mail válido.",
    val_policy_title: "Aceite os termos",
    val_policy_text: "Você deve aceitar a política de privacidade para enviar sua mensagem.",

    // --- NOSOTROS (About Us) ---
    about_title: "Conheça a Euno 360",
    about_subtitle: "Empoderamos pessoas. Impulsionamos resultados.",
    mision_title: "Missão",
    mision_desc: "Transformar empresas e potencializar marcas pessoais através da integração orgânica do coaching ontológico, gestão emocional, marketing e vendas, gerando estratégias conscientes, conversas efetivas e ações que impulsionam resultados extraordinários com bem-estar sustentável.",
    vision_title: "Visão",
    vision_desc: "Ser a consultoria referência na América Latina na humanização dos negócios, demonstrando que transparência, alegria e consciência são a base de uma rentabilidade sustentável, equipes comprometidas e marcas pessoais sólidas.",
    valores_title: "Nossos Valores",
    
    val_honestidad: "Honestidade",
    val_honestidad_desc: "Coerência total entre o que dizemos e fazemos.",
    val_transparencia: "Transparência",
    val_transparencia_desc: "Processos claros, comunicação aberta e sem 'letras miúdas'.",
    val_alegria: "Alegria",
    val_alegria_desc: "Acreditamos no bem-estar emocional como motor do sucesso profissional e organizacional.",
    val_pasion: "Paixão",
    val_pasion_desc: "O que fazemos nos move e transmitimos isso em cada processo e resultado.",
    val_posibilidad: "Possibilidade",
    val_posibilidad_desc: "Confiamos no potencial das pessoas e na capacidade de criar novas realidades.",
    val_equipo: "Trabalho em equipe",
    val_equipo_desc: "Promovemos a colaboração genuína para potencializar resultados e impacto.",
    val_prosperidad: "Prosperidade Coletiva",
    val_prosperidad_desc: "O sucesso é real quando beneficia todas as partes envolvidas (Ganha-Ganha).",
    val_conciencia: "Consciência",
    val_conciencia_desc: "Toda transformação começa com uma nova forma de observar.",
    val_resultados: "Orientação a resultados",
    val_resultados_desc: "Desenhamos ações que impactam tanto o negócio quanto as pessoas.",

    // --- SERVICIOS (Detalles) ---
    serv_ind_title: "Coaching Individual",
    serv_ind_subtitle: "Ontológico & Desenvolvimento Pessoal",
    serv_ind_tagline: "Focado em pessoas que querem gerar mudanças concretas em sua vida pessoal ou profissional.",
    serv_ind_item1: "Processos de coaching ontológico 1:1",
    serv_ind_item2: "Gestão emocional aplicada à vida cotidiana",
    serv_ind_item3: "Apoio na tomada de decisões",
    serv_ind_item4: "Desenvolvimento de autoconhecimento e liderança pessoal",
    serv_ind_item5: "Reconfiguração de crenças limitantes",
    serv_ind_item6: "Coaching para momentos de mudança (trabalho, pessoal, crise, etc.)",
    serv_ind_dif1: "Integração de coaching ontológico + psicoeducação + neurociências",
    serv_ind_dif2: "Trabalho profundo na linguagem, emoções e corpo",
    serv_ind_dif3: "Ferramentas práticas e aplicáveis desde a primeira sessão",

    serv_eje_title: "Coaching Executivo",
    serv_eje_subtitle: "Liderança & Alta Exigência",
    serv_eje_tagline: "Orientado para líderes, gerência média e perfis com responsabilidade de gestão.",
    serv_eje_item1: "Coaching para desenvolvimento de liderança",
    serv_eje_item2: "Gestão emocional em ambientes de alta exigência",
    serv_eje_item3: "Tomada de decisões estratégicas",
    serv_eje_item4: "Desenvolvimento de habilidades conversacionais (feedback, pedidos, conversas difíceis)",
    serv_eje_item5: "Apoio em processos de mudança organizacional",
    serv_eje_item6: "Coaching para melhoria de desempenho e resultados",
    serv_eje_dif1: "Abordagem ontológica aplicada ao negócio",
    serv_eje_dif2: "Integração de inteligência emocional + visão sistêmica",
    serv_eje_dif3: "Trabalho sobre o impacto do líder no clima e resultados",

    serv_org_title: "Coaching Organizacional",
    serv_org_subtitle: "Cultura & Relacionamentos Internos",
    serv_org_tagline: "Para empresas que buscam melhorar a cultura, resultados e relacionamentos internos.",
    serv_org_item1: "Diagnóstico cultural e conversacional",
    serv_org_item2: "Intervenções em equipes de trabalho",
    serv_org_item3: "Programas de liderança organizacional",
    serv_org_item4: "Melhoria do ambiente de trabalho",
    serv_org_item5: "Gestão de conflitos e mediação",
    serv_org_item6: "Desenho de conversas efetivas na organização",
    serv_org_dif1: "Abordagem a partir da cultura e não apenas do comportamento",
    serv_org_dif2: "Intervenções práticas com impacto nos resultados",
    serv_org_dif3: "Integração de coaching + emocionalidade + negócios",

    serv_mentoria_title: "Mentoria em Vendas",
    serv_mentoria_subtitle: "Identidade & Fechamento Comercial",
    serv_mentoria_tagline: "Para vendedores, empreendedores ou equipes comerciais.",
    serv_mentoria_item1: "Mentoria 1:1 para vendedores",
    serv_mentoria_item2: "Apoio em processos de fechamento",
    serv_mentoria_item3: "Desenvolvimento de habilidades comerciais",
    serv_mentoria_item4: "Gestão emocional em vendas (rejeição, frustração, pressão por objetivos)",
    serv_mentoria_item5: "Construção de identidade comercial",
    serv_mentoria_item6: "Estratégias de fidelização e experiência do cliente",
    serv_mentoria_dif1: "Trabalho sobre o 'ser vendedor', não apenas técnicas",
    serv_mentoria_dif2: "Integração de coaching + vendas + emocionalidade",
    serv_mentoria_dif3: "Foco em resultados sustentáveis (não apenas scripts)",

    serv_cap_title: "Treinamentos de Vendas",
    serv_cap_subtitle: "Treinamento Comercial Corporativo",
    serv_cap_tagline: "Para equipes comerciais de empresas.",
    serv_cap_item1: "Programas de formação em vendas",
    serv_cap_item2: "Técnicas de fechamento e negociação",
    serv_cap_item3: "Experiência do cliente (CX)",
    serv_cap_item4: "Comunicação eficaz em vendas",
    serv_cap_item5: "Lidando com objeções",
    serv_cap_item6: "Venda consultiva",
    serv_cap_item7: "Treinamento em soft skills para vendedores",
    serv_cap_dif1: "Treinamentos vivenciais (não teóricos)",
    serv_cap_dif2: "Integração de coaching ontológico",
    serv_cap_dif3: "Aplicação direta no local de trabalho",
    serv_cap_dif4: "Foco no NPS e na qualidade do atendimento",

    serv_int_title: "Programas Integrais",
    serv_int_subtitle: "Abordagem 360° Premium",
    serv_int_tagline: "Proposta premium para organizações focada em Coaching + Vendas + Cultura.",
    serv_int_item1: "Programas de transformação cultural",
    serv_int_item2: "Alinhamento entre liderança e equipes comerciais",
    serv_int_item3: "Integração da gestão emocional nas vendas",
    serv_int_item4: "Desenvolvimento de cultura centrada no cliente",
    serv_int_item5: "Acompanhamento + medição de impacto",
    serv_int_dif1: "Abordagem holística e simultânea dos três eixos do sucesso corporativo",
    serv_int_dif2: "Medições precisas de clima, conversão de vendas e eficácia operacional"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('es');

  // Función traductora 't'
  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);